### ISSUE TITLE
Rationale?

### ISSUE THREAD

**Issue by AdamWagner** [szymonkaliski/hhtwm#2]
Great to see your interest in tiling wm for macos. I see in your dotfiles that you’ve used chunkwm. I currently use chunkwm and would like to know what motivated you to roll your own with hammerspoon?

Thanks!

**Comment by szymonkaliski** [comment]
Hm, multiple reasons really:

0. isn't writing and using your own wm like the ultimate nerd cred?
1. I prefer my own stuff to other people's stuff in general ;) it's also easier to hack and change your own codebase than someone elses
2. chunkwm didn't work with multiple displays like I wanted it to (I don't remember the details though)
3. chunkwm was loosing the whole layout when it was restarted - hhtwm stores layouts between reloads
4. I was already using hammerspoon for bunch of other stuff, and running two apps that do window managing at the same time felt _wrong_

**Comment by AdamWagner** [comment]
@szymonkaliski - thanks a lot! Makes sense, and helps me understand if I should give it a spin. #3 is a pretty compelling reason for me to get Hammerspoon wired up again ;-)
