### ISSUE TITLE
Docs : What do the layouts mean?

### ISSUE THREAD

**Issue by JoshuaCrewe** [szymonkaliski/hhtwm#3]
Been playing around with this for a few weeks now and enjoying the experience. I have been trying to piece together my own config from your own dotfiles and some other reasources for configuring Hammerspoon.

I was wondering if there was potential to explain what the intention is with each of the layout options. Specifically monocle and cards.

Happy to help with the start of  PR if that is welcome.

👍 for a nice tiling window manager on macOS

**Comment by szymonkaliski** [comment]
Hey, sure, PRs are welcome.

I mainly use monocle on a laptop screen, and switch between multiple windows with some custom shortcuts to cycle through windows back/forth.

Cards is like monocle but gives little offset, so you can see you have more than one window; I don't use it much really.

**Comment by JoshuaCrewe** [comment]
When navigating through windows using your shortcuts presumably we are talking about North, South, East, West ? So these wouldn't work when in monocle or cards layout as they are stacked? Is that right?

How are the windows layed out when using Monocle or Cards layout? Like what are the rules ?

**Comment by szymonkaliski** [comment]
With monocle I'm usually using these shortcuts: https://github.com/szymonkaliski/dotfiles/blob/master/Dotfiles/hammerspoon/bindings/focus.lua#L68-L69 to cycle between windows on given screen.

The windows are laid out in order of creation (newest on top) - https://github.com/szymonkaliski/hhtwm/blob/master/hhtwm/init.lua#L787

**Comment by JoshuaCrewe** [comment]
Beautiful. I am going to have another dig around and see if I can make sense of what I have find.

If my notes are of any use I will open a PR

Thanks very much!

**Comment by JoshuaCrewe** [comment]
As a quick update : 
I found that when using this feature I have every window open full screen and either alt tab between them or using a Hyper Key shortcut. It works a real dream and so I have not found the need to dig into the other features.

I didn't want it to seem like I was holding anything back.

👍 thanks for writing software that solves my problems.
