### ISSUE TITLE
module 'hs._asm.axuielement' not found

### ISSUE THREAD

**Issue by realav** [szymonkaliski/hhtwm#5]
I got this error.

`*** ERROR: ...app/Contents/Resources/extensions/hs/_coresetup/init.lua:597: module 'hs._asm.axuielement' not found:
	no field package.preload['hs._asm.axuielement']
	no file '/Users/xxx/.hammerspoon/hs/_asm/axuielement.lua'
	no file '/Users/xxx/.hammerspoon/hs/_asm/axuielement/init.lua'
	no file '/Users/xxx/.hammerspoon/Spoons/hs/_asm/axuielement.spoon/init.lua'
	no file '/usr/local/share/lua/5.3/hs/_asm/axuielement.lua'
	no file '/usr/local/share/lua/5.3/hs/_asm/axuielement/init.lua'
	no file '/usr/local/lib/lua/5.3/hs/_asm/axuielement.lua'
	no file '/usr/local/lib/lua/5.3/hs/_asm/axuielement/init.lua'
	no file './hs/_asm/axuielement.lua'
	no file './hs/_asm/axuielement/init.lua'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/hs/_asm/axuielement.lua'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/hs/_asm/axuielement/init.lua'
	no file '/Users/xxx/.hammerspoon/hs/_asm/axuielement.so'
	no file '/usr/local/lib/lua/5.3/hs/_asm/axuielement.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './hs/_asm/axuielement.so'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/hs/_asm/axuielement.so'
	no file '/Users/xxx/.hammerspoon/hs.so'
	no file '/usr/local/lib/lua/5.3/hs.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './hs.so'
	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/hs.so'
stack traceback:
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:597: in function 'require'
	/Users/xxx/.hammerspoon/hhtwm/init.lua:3: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:597: in function 'require'
	/Users/xxx/.hammerspoon/init.lua:1: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:648: in function 'hs._coresetup.setup'
	(...tail calls...)
`

<img width="419" alt="Screenshot 2020-08-28 at 2 16 33 AM" src="https://user-images.githubusercontent.com/3285444/91493178-89278200-e8d4-11ea-8450-0fc291e0b267.png">

Hammerspoon Version 0.9.78 (5164)
macOS 10.15.6

**Comment by szymonkaliski** [comment]
`axuielement` has to be inside `hs/_asm` folder - looks like you have it inside `hs` only, but not in `_asm`:

![Screenshot 2020-08-28 at 09 38 24](https://user-images.githubusercontent.com/1040420/91534697-41275000-e912-11ea-95d7-00069a622530.png)

**Comment by realav** [comment]
After correcting the directory structure, I got this...

`2020-08-28 13:13:19: -- Lazy extension loading enabled
2020-08-28 13:13:19: -- Loading ~/.hammerspoon/init.lua
2020-08-28 13:13:47: *** ERROR: error loading module 'hs.axuielement.internal' from file '/Users/xxx/.hammerspoon/hs/axuielement/internal.so':
	dlopen(/Users/xxx/.hammerspoon/hs/axuielement/internal.so, 6): no suitable image found.  Did find:
	/Users/xxx/.hammerspoon/hs/axuielement/internal.so: code signature in (/Users/xxx/.hammerspoon/hs/axuielement/internal.so) not valid for use in process using Library Validation: library load disallowed by system policy
stack traceback:
	[C]: in ?
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:597: in function 'require'
	/Users/xxx/.hammerspoon/hs/_asm/axuielement/init.lua:46: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:597: in function 'require'
	/Users/xxx/.hammerspoon/hhtwm/init.lua:3: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:597: in function 'require'
	/Users/xxx/.hammerspoon/init.lua:1: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:648: in function 'hs._coresetup.setup'
	(...tail calls...)
2020-08-28 13:13:53: -- Lazy extension loading enabled
2020-08-28 13:13:53: -- Loading ~/.hammerspoon/init.lua
2020-08-28 13:13:55: *** ERROR: error loading module 'hs.axuielement.internal' from file '/Users/xxx/.hammerspoon/hs/axuielement/internal.so':
	dlopen(/Users/xxx/.hammerspoon/hs/axuielement/internal.so, 6): Symbol not found: _lua_newuserdatauv
  Referenced from: /Users/xxx/.hammerspoon/hs/axuielement/internal.so
  Expected in: /Applications/Hammerspoon.app/Contents/MacOS/../Frameworks/LuaSkin.framework/Versions/A/LuaSkin
 in /Users/xxx/.hammerspoon/hs/axuielement/internal.so
stack traceback:
	[C]: in ?
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:597: in function 'require'
	/Users/xxx/.hammerspoon/hs/_asm/axuielement/init.lua:46: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:597: in function 'require'
	/Users/xxx/.hammerspoon/hhtwm/init.lua:3: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:597: in function 'require'
	/Users/xxx/.hammerspoon/init.lua:1: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:648: in function 'hs._coresetup.setup'
	(...tail calls...)
2020-08-28 13:13:59: -- Lazy extension loading enabled
2020-08-28 13:13:59: -- Loading ~/.hammerspoon/init.lua
2020-08-28 13:13:59: *** ERROR: error loading module 'hs.axuielement.internal' from file '/Users/xxx/.hammerspoon/hs/axuielement/internal.so':
	dlopen(/Users/xxx/.hammerspoon/hs/axuielement/internal.so, 6): Symbol not found: _lua_newuserdatauv
  Referenced from: /Users/xxx/.hammerspoon/hs/axuielement/internal.so
  Expected in: /Applications/Hammerspoon.app/Contents/MacOS/../Frameworks/LuaSkin.framework/Versions/A/LuaSkin
 in /Users/xxx/.hammerspoon/hs/axuielement/internal.so
stack traceback:
	[C]: in ?
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:597: in function 'require'
	/Users/xxx/.hammerspoon/hs/_asm/axuielement/init.lua:46: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:597: in function 'require'
	/Users/xxx/.hammerspoon/hhtwm/init.lua:3: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:597: in function 'require'
	/Users/xxx/.hammerspoon/init.lua:1: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:648: in function 'hs._coresetup.setup'
	(...tail calls...)
`
