### ISSUE TITLE
Error loading module 'hs.axuielement.internal' from file internal.so

### ISSUE THREAD

**Issue by realav** [szymonkaliski/hhtwm#6]
I got this error...

`2020-08-29 13:25:20: -- Lazy extension loading enabled
2020-08-29 13:25:20: -- Loading ~/.hammerspoon/init.lua
2020-08-29 13:25:20: *** ERROR: error loading module 'hs.axuielement.internal' from file '/Users/xxx/.hammerspoon/hs/axuielement/internal.so':
	dlopen(/Users/xxx/.hammerspoon/hs/axuielement/internal.so, 6): Symbol not found: _lua_newuserdatauv
  Referenced from: /Users/xxx/.hammerspoon/hs/axuielement/internal.so
  Expected in: /Applications/Hammerspoon.app/Contents/MacOS/../Frameworks/LuaSkin.framework/Versions/A/LuaSkin
 in /Users/xxx/.hammerspoon/hs/axuielement/internal.so
stack traceback:
	[C]: in ?
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:597: in function 'require'
	/Users/xxx/.hammerspoon/hs/_asm/axuielement/init.lua:46: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:597: in function 'require'
	/Users/xxx/.hammerspoon/hhtwm/init.lua:3: in main chunk
	[C]: in function 'rawrequire'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:597: in function 'require'
	/Users/xxx/.hammerspoon/init.lua:1: in main chunk
	[C]: in function 'xpcall'
	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:648: in function 'hs._coresetup.setup'
	(...tail calls...)
`

**Comment by szymonkaliski** [comment]
This doesn't seem like HHTWM error but an `axuielement` one, I'm not sure if I can help you here.
